version: '3.9'
services:
  socket:
    image: node:18.4.0-alpine
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "${PORT-3002}:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      CLIENT_URL: "${CLIENT_URL}"
      CLIENT_API_KEY: "${CLIENT_API_KEY}"
    command: "yarn dev"
  redis:
    image: redis:7.0.2-alpine
    restart: unless-stopped
    command: redis-server
